apiVersion: v1
kind: Secret
metadata:
  name: mysql-clever-secrets
type: Opaque
data:
  DB_HOST: YmJ4cWNrNGx4dHF1aHdud295bGItbXlzcWwuc2VydmljZXMuY2xldmVyLWNsb3VkLmNvbQ==
  DB_USER: dXlpaHN4Z3FlbWc5emJncA==
  DB_PASSWORD: YUNYUHB4T3ZkbDUybFp5RTNyMWg=
  DB_NAME: YmJ4cWNrNGx4dHF1aHdud295bGI=
